Update deployments.createPrediction to use wait
replicate/replicate-javascript pull request #322
Opened 2024-10-15 10:27 UTC by evilstreak

A first draft of this interface used `block`, but we ended up going with `wait` (as either a boolean or a number) for the predictions.createPrediction method. This commit brings the two implementations inline, and deprecates the `block` parameter.

Note: it would be nice to emit a warning about the deprecation if this method is called with the `block` parameter, but I'm not sure how to do that reliably across platforms. Advice welcome!

2024-10-15 15:02 UTC, meatballhat approved these changes
⏳

2024-10-16 09:42 UTC, aron requested changes
Hmm, this is a bug rather than a feature. The final interface was always intended to be create. I think we just remove the `block` param entirely here and keep the implementation as you have it.

https://github.com/replicate/replicate-javascript/blob/main/index.d.ts#L210-L221

2024-10-16 14:20 UTC, evilstreak commented
@aron I've completely removed the old `block` parameter

2024-10-16 14:21 UTC, aron approved these changes
👏 Ta very much

2024-10-16 14:23 UTC, merged